//! `#[derive(Store)]`: a signal per field.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{spanned::Spanned, Data, DeriveInput, Fields};

/// Expand `#[derive(Store)]`: a `NameStore` with one signal per field.
///
/// # Errors
///
/// Fails with a spanned error when the input does not parse or is invalid.
pub fn expand_store(input: TokenStream) -> syn::Result<TokenStream> {
    let input: DeriveInput = syn::parse2(input)?;
    let name = &input.ident;
    let error = || {
        syn::Error::new(
            input.span(),
            "#[derive(Store)] works on structs with named fields",
        )
    };
    let Data::Struct(data) = &input.data else {
        return Err(error());
    };
    let Fields::Named(fields) = &data.fields else {
        return Err(error());
    };
    if !input.generics.params.is_empty() {
        return Err(syn::Error::new(
            input.generics.span(),
            "#[derive(Store)] structs cannot be generic",
        ));
    }
    let store = format_ident!("{}Store", name);
    let visibility = &input.vis;
    let state = quote!(::rok_ui::state);
    let mut struct_fields = Vec::new();
    let mut initializers = Vec::new();
    let mut methods = Vec::new();
    let mut snapshot = Vec::new();
    let mut set_all = Vec::new();
    for field in &fields.named {
        let Some(ident) = field.ident.as_ref() else {
            return Err(syn::Error::new(field.span(), "expected a named field"));
        };
        if ["new", "get", "set", "update"].contains(&ident.to_string().as_str()) {
            return Err(syn::Error::new(
                ident.span(),
                "this field name clashes with a store method; rename it",
            ));
        }
        let ty = &field.ty;
        let setter = format_ident!("set_{}", ident);
        let updater = format_ident!("update_{}", ident);
        let read_doc = format!("The `{ident}` field. Reading it tracks only this field.");
        let set_doc = format!("Set the `{ident}` field; only its readers re-render.");
        let update_doc = format!("Change the `{ident}` field in place.");
        struct_fields.push(quote!(#ident: (#state::ReadSignal<#ty>, #state::WriteSignal<#ty>)));
        initializers.push(quote!(#ident: #state::create_signal(value.#ident)));
        methods.push(quote! {
            #[doc = #read_doc]
            #[must_use]
            pub fn #ident(&self) -> #state::ReadSignal<#ty> {
                self.#ident.0.clone()
            }

            #[doc = #set_doc]
            pub fn #setter(&self, value: #ty) {
                self.#ident.1.set(value);
            }

            #[doc = #update_doc]
            pub fn #updater(&self, update: impl FnOnce(&mut #ty)) {
                self.#ident.1.update(update);
            }
        });
        snapshot.push(quote!(#ident: self.#ident.0.get()));
        set_all.push(quote!(self.#ident.1.set(value.#ident);));
    }
    let doc = format!("A fine-grained store for [`{name}`]: one signal per field, so views re-render only for the fields they read. Generated by `#[derive(Store)]`.");
    Ok(quote! {
        #[doc = #doc]
        #[derive(Clone)]
        #visibility struct #store {
            #(#struct_fields,)*
        }

        impl #store {
            /// A store holding `value`.
            #[must_use]
            pub fn new(value: #name) -> Self {
                Self { #(#initializers,)* }
            }

            #(#methods)*

            /// Every field, as a value. Reading it tracks every field.
            #[must_use]
            pub fn get(&self) -> #name {
                #name { #(#snapshot,)* }
            }

            /// Replace every field.
            pub fn set(&self, value: #name) {
                #state::batch(|| { #(#set_all)* });
            }
        }

        impl #name {
            /// A fine-grained store holding this value.
            #[must_use]
            pub fn into_store(self) -> #store {
                #store::new(self)
            }
        }
    })
}
